import pandas as pd

file_paths = ["/private10/Projects/Efi/AML/rMATS/5Azacytidine_FB23-2/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/5Azacytidine_FB23-2/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/5Azacytidine_FB23-2/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/5Azacytidine_FB23-2/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/5Azacytidine_FB23-2/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_5Azacytidine/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_5Azacytidine/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_5Azacytidine/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_5Azacytidine/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_5Azacytidine/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_FB23-2/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_FB23-2/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_FB23-2/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_FB23-2/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_FB23-2/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Indisulam/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Indisulam/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Indisulam/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Indisulam/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Indisulam/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_18h/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_18h/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_18h/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_18h/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_18h/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_6h/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_6h/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_6h/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_6h/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_Mock_6h/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_PladienolideB/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_PladienolideB/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_PladienolideB/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_PladienolideB/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Control_PladienolideB/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Indisulam_PladienolideB/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Indisulam_PladienolideB/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Indisulam_PladienolideB/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Indisulam_PladienolideB/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Indisulam_PladienolideB/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_5Azacytidine/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_5Azacytidine/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_5Azacytidine/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_5Azacytidine/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_5Azacytidine/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_FB23-2/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_FB23-2/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_FB23-2/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_FB23-2/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock18h_FB23-2/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Indisulam/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Indisulam/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Indisulam/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Indisulam/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Indisulam/SE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Pladienolide/A3SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Pladienolide/A5SS/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Pladienolide/MXE/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Pladienolide/RI/netMHC_rank0.5_StrongBinders_All.csv",
"/private10/Projects/Efi/AML/rMATS/Mock6h_Pladienolide/SE/netMHC_rank0.5_StrongBinders_All.csv"
]  # Add your file paths here

dataframes = [pd.read_csv(file) for file in file_paths]
combined_dataframe = pd.concat(dataframes, ignore_index=True)

combined_dataframe.to_csv("/private10/Projects/Efi/AML/rMATS/netMHCcombined.csv", index=False)
